- id: '1736200159144'
  alias: Turn On Fish Lights
  description: Turns on the Fish Tank lights at 6:30 am
  triggers:
  - at: 06:30:00
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id:
      - switch.fish_tank
    action: switch.turn_on
    data: {}
  mode: single
- id: '1736200267958'
  alias: Turn Off Fish Lights
  description: Turn Off Fish Lights at 7:30 pm
  triggers:
  - at: '19:30:00'
    trigger: time
  conditions: []
  actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.fish_tank
  mode: single
- id: '1736200586902'
  alias: Turn on office for work
  description: Turn on office for work weekdays at 6:30 am
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.time_for_work_2
  mode: single
- id: '1736201001617'
  alias: Pantry Light on/off
  description: Turns on or off the Pantry light depending on state of door sensor
  triggers:
  - entity_id:
    - binary_sensor.pantry_door_opening
    trigger: state
    to:
    from:
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.pantry_door_opening
      state: 'on'
    then:
    - action: switch.turn_on
      data: {}
      target:
        device_id: 9c6123c4d1b9823b2545b66aaaf8570e
    else:
    - action: switch.turn_off
      data: {}
      target:
        device_id: 9c6123c4d1b9823b2545b66aaaf8570e
  mode: single
- id: '1736201460884'
  alias: Family Room LED's
  description: Turn on LED's if TV is turned on, and turn off if not on
  triggers:
  - type: changed_states
    device_id: 9d81494c52d6e78ab4255bea9b9b1890
    entity_id: 62bd6831ee73004336f0c134ff408550
    domain: media_player
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.family_room_tv
        state: 'on'
      sequence:
      - type: turn_on
        device_id: 3eb1e15ffb266f5660ffa4c2c8ef08a9
        entity_id: 5ecb1cc9813959c67d7ce875ebd0fa7c
        domain: switch
      - type: turn_on
        device_id: 3eb1e15ffb266f5660ffa4c2c8ef08a9
        entity_id: 5978eb2137178b6e00d2db9b37241c2b
        domain: switch
    default:
    - type: turn_off
      device_id: 3eb1e15ffb266f5660ffa4c2c8ef08a9
      entity_id: 5ecb1cc9813959c67d7ce875ebd0fa7c
      domain: switch
  mode: single
- id: '1736201652503'
  alias: Master TV LED's
  description: Turn on master TV LED when TV turns on, else turn off
  triggers:
  - type: changed_states
    device_id: f20fc61cd6683f5e70b2e311302e8ae1
    entity_id: 93954116b4ec2cfcc7ed6716c3b71079
    domain: media_player
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.master_tv
        state: 'on'
      sequence:
      - target:
          device_id: 3673c0b2fe68b3346e7d0d2fa47c2184
        data:
          brightness_pct: 95
        action: light.turn_on
    default:
    - target:
        device_id: 3673c0b2fe68b3346e7d0d2fa47c2184
      action: light.turn_off
      data: {}
  mode: single
- id: '1736202150288'
  alias: Side garage door open
  description: If Side Garage door opens after 9:30 PM, flash hall night light red;
    return to light blue at 50% when closed
  triggers:
  - entity_id: binary_sensor.side_garage_door
    trigger: state
  conditions:
  - condition: time
    after: '21:30:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.side_garage_door
        state: 'on'
      sequence:
      - target:
          entity_id: light.hall_night_light
        data:
          rgb_color:
          - 242
          - 7
          - 7
          flash: short
        action: light.turn_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.side_garage_door
        state: 'off'
      sequence:
      - target:
          entity_id: light.hall_night_light
        data:
          rgb_color:
          - 173
          - 216
          - 230
          brightness_pct: 50
        action: light.turn_on
  mode: single
- id: '1736202452093'
  alias: Dryer has finished running
  description: Announce on speakers when dryer finishes
  triggers:
<<<<<<< HEAD
<<<<<<< HEAD
  - entity_id:
    - sensor.dryer_machine_state
    trigger: state
    from: 'On'
    to: 'Off'
=======
  - entity_id: binary_sensor.dryer_remote_status
=======
  - entity_id:
    - sensor.dryer_machine_state
>>>>>>> 2ae4e03 (added db update)
    from: 'on'
    to: 'off'
    trigger: state
>>>>>>> e9374e6 (updated automations)
  conditions:
  - condition: time
    after: 07:00:00
    before: '23:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  actions:
<<<<<<< HEAD
  - data:
      volume_level: 0.5
    action: media_player.volume_set
    target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
=======
  - target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
    data:
      volume_level: 0.75
    action: media_player.volume_set
>>>>>>> e9374e6 (updated automations)
  - data:
      cache: false
      entity_id: media_player.gh_ha_all_speakers
      message: The Dryer has finished running.
    action: tts.cloud_say
  mode: single
- id: '1736202825725'
  alias: Washer is finished running
  description: Announce on speakers when washer finishes
  triggers:
<<<<<<< HEAD
<<<<<<< HEAD
  - entity_id:
    - sensor.dishwasher_machine_state
=======
  - entity_id: binary_sensor.washer_remote_status
    from: 'on'
=======
  - entity_id:
    - sensor.washer_state
    from:
>>>>>>> 2ae4e03 (added db update)
    to: 'off'
>>>>>>> e9374e6 (updated automations)
    trigger: state
  conditions:
  - condition: time
    after: 07:00:00
    before: '23:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
<<<<<<< HEAD
  - data:
      volume_level: 0.5
=======
  - target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
    data:
      volume_level: 0.75
>>>>>>> e9374e6 (updated automations)
    action: media_player.volume_set
    target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
  - data:
      cache: true
      entity_id: media_player.gh_ha_all_speakers
      message: The washer has finished running. Please move clothes to the dryer.
    action: tts.cloud_say
  mode: single
- id: '1736203243743'
  alias: Let's Relax
  description: ''
  triggers:
  - event: sunset
    offset: '-300'
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: scene.lets_relax_scene
    action: scene.turn_on
  mode: single
- id: '1736205456810'
  alias: Time for Bed
  description: Runs time for bed scene and delays turning off Kitchen accent light
    for 5 mins
  triggers:
  - at: '23:30:00'
    trigger: time
  conditions:
  - condition: device
    type: is_on
    device_id: 63e3772dc5ae26e489f92824bed0e5b4
    entity_id: e4a2c7de3a7b122aa5d9750619eabdd1
    domain: light
  actions:
  - action: script.turn_on
    data: {}
    target:
      entity_id: script.time_for_bed_script_3
  mode: single
- id: '1736205770847'
  alias: Play Media when doorbell is pushed
  description: Plays doorbell sound on speaker when motion is detected
  triggers:
  - type: occupied
    device_id: 01c1ddd4016a5da445a3002653c9624b
    entity_id: 9fb24bad40c10c2347807ec9424e0f08
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: 07:00:00
    before: '21:00:00'
  actions:
<<<<<<< HEAD
  - data:
      volume_level: 0.75
    action: media_player.volume_set
    target:
      device_id: 112dc83284137f5753a360ff1b508e15
  - target:
      device_id:
      - 8618887208e1a4bfba2758455d4547f9
      - 112dc83284137f5753a360ff1b508e15
    data:
=======
  - target:
      device_id: 112dc83284137f5753a360ff1b508e15
    data:
      volume_level: 0.75
    action: media_player.volume_set
  - target:
      device_id:
      - 112dc83284137f5753a360ff1b508e15
    data:
      enqueue: add
      metadata: {}
>>>>>>> e9374e6 (updated automations)
      media:
        media_content_id: media-source://media_source/local/Doorbell/Someone knocking
          on the door.mp3
        media_content_type: audio/mpeg
        metadata: {}
<<<<<<< HEAD
      enqueue: add
=======
>>>>>>> e9374e6 (updated automations)
    action: media_player.play_media
  mode: single
- id: '1757427938275'
  alias: Dishwasher has finished running
  description: Announces clean dishes and flashes kitchen nightlight
  triggers:
  - entity_id: select.dishwasher
    from: run
    to: stop
    trigger: state
  conditions:
  - condition: time
    after: 08:00:00
    before: '22:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
<<<<<<< HEAD
  - data:
=======
  - target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
    data:
>>>>>>> e9374e6 (updated automations)
      volume_level: 0.5
    action: media_player.volume_set
    target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
  - target:
      entity_id: tts.home_assistant_cloud
    data:
      cache: true
      media_player_entity_id: media_player.gh_ha_all_speakers
      message: The dishes are clean
    action: tts.speak
  - target:
      entity_id: script.flash_kitchen_nightlight_when_dishes_are_clean
    data: {}
    action: script.turn_on
  mode: single
- id: '1757439538889'
  alias: Front of house lights on at sunset
  description: ''
  use_blueprint:
    path: CyanAutomation/lights_on_at_sunset.yaml
    input:
      target_light:
        device_id:
        - 12eb2902fec46e4063b6bca537501535
        - 235b48bf9f8bbde2f7dd3f26f075965e
        - bb125b76b148dd38af12452535a4b5c4
      target_brightness: 25
- id: '1757439642812'
  alias: Front of House Lights OFF at Sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 12eb2902fec46e4063b6bca537501535
    entity_id: 222f830c1d275415369f6c0f867d44de
    domain: light
  - type: turn_off
    device_id: bb125b76b148dd38af12452535a4b5c4
    entity_id: 938c77cb715fd71ef33b1e3953286b0d
    domain: light
  - type: turn_off
    device_id: 235b48bf9f8bbde2f7dd3f26f075965e
    entity_id: 63a99f6dc52aab8ffd1440678506e914
    domain: light
  mode: single
- id: '1757439807215'
  alias: Garage Freezer door open
  description: ''
  triggers:
  - type: opened
    device_id: ca70f08f74ed5159305440dd9f34e0f1
    entity_id: 71b639894f45486886bb3388d2c51ff5
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
<<<<<<< HEAD
  conditions: []
  actions:
  - action: media_player.volume_set
    target:
      device_id:
      - 2bb886d6e9807e3973f0378a059d2100
    data:
      volume_level: 0.66
    action: media_player.volume_set
  - data:
      cache: false
      entity_id: media_player.gh_ha_all_speakers
      message: The  Garage Freezer door is open, Please close immediately.
  mode: single
- id: '1757440249644'
  alias: Office TV - Couch Light Sync
  description: Couch light turns purple when TV is playing, white when idle or off
  triggers:
  - entity_id: media_player.office_roku_tv
    to: playing
    trigger: state
  - entity_id: media_player.office_roku_tv
    to: idle
    trigger: state
  - entity_id: media_player.office_roku_tv
    to: 'off'
    trigger: state
=======
    trigger: device
  conditions: []
>>>>>>> e9374e6 (updated automations)
  actions:
  - target:
      device_id: 2bb886d6e9807e3973f0378a059d2100
    data:
      volume_level: 0.66
    action: media_player.volume_set
  - data:
      cache: false
      entity_id: media_player.gh_ha_all_speakers
      message: The Garage Freezer door is open. Please close it immediately.
    action: tts.cloud_say
  mode: single
- id: '1757440249644'
  alias: Office TV - Couch Light Sync
  description: Couch light turns purple when TV is playing, white when idle or off
  triggers:
  - entity_id: media_player.office_roku_tv
    trigger: state
  actions:
  - target:
      entity_id: light.office_couch_lamp
    data:
      rgb_color: "{% if states('media_player.office_roku_tv') == 'playing' %}\n  [75,
        0, 130]\n{% else %}\n  [255, 255, 255]\n{% endif %}\n"
      brightness: "{% if states('media_player.office_roku_tv') == 'playing' %}\n  180\n{%
        else %}\n  220\n{% endif %}\n"
    action: light.turn_on
  mode: single
- id: '1757442161116'
  alias: Bench Light on when dark and motion detected
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      include_state_control: state_control_enabled
      state_control_activation_state: 'on'
      state_control_entity: binary_sensor.interior_garage_g3_flex_is_dark
      motion_trigger:
      - binary_sensor.interior_garage_g3_flex_motion
      light_switch:
        entity_id: switch.bench_lights
      time_delay: 1
- id: '1757451967553'
  alias: Garage Fan Temperature Control
  description: Turns fan on above 90°F, off below 82°F
  triggers:
  - entity_id: weather.williams_s_casa
    attribute: temperature
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: weather.williams_s_casa
        attribute: temperature
        above: 90
      sequence:
      - target:
          entity_id: switch.garage_fan
        action: switch.turn_on
    - conditions:
      - condition: numeric_state
        entity_id: weather.williams_s_casa
        attribute: temperature
        below: 82
      sequence:
      - target:
          entity_id: switch.garage_fan
        action: switch.turn_off
  mode: single
- id: '1757453682834'
  alias: Front Door Motion Boost
  description: Turn on front porch light to full brightness, then restore
  triggers:
  - entity_id: switch.g4_doorbell_detections_person
    to: 'on'
    trigger: state
  conditions:
  - condition: sun
    after: sunset
  actions:
  - action: script.boost_light_temporarily
    data: {}
  mode: single
- id: '1757454208105'
  alias: Driveway Motion Boost
  description: turn on driveway lights to full brightness, then restore
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.driveway_g3_flex_motion
    to: 'on'
  conditions:
  - condition: sun
    after: sunset
  actions:
  - action: script.boost_light_temporarily_driveway_lights
    data: {}
  mode: single
- id: '1757644001455'
<<<<<<< HEAD
  alias: Gabby Home After Dark
  description: Turns on Gabby's Deck Light when she gets home after dark
  triggers:
  - device_id: ed076af17b373aace55d0777ddd82b16
    domain: device_tracker
    entity_id: c2c45289e914d1fc40f452ed3eebe619
    type: enters
    trigger: device
    zone: zone.home
  conditions:
  - condition: sun
    after: sunset
  actions:
  - type: turn_on
    device_id: 0208fe8795d2d0bde39bd0171e269e5b
    entity_id: aad564fa6fb9364c27125469a28f0c2d
    domain: light
    brightness_pct: 75
=======
  alias: Side garage door open
  description: If Side Garage door opens after 9:30 PM, flash hall night light red;
    return to light blue at 50% when closed
  triggers:
  - entity_id: binary_sensor.side_garage_door
    trigger: state
  conditions:
  - condition: time
    after: '21:30:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.side_garage_door
        state: 'on'
      sequence:
      - target:
          entity_id: light.hall_night_light
        data:
          rgb_color:
          - 242
          - 7
          - 7
          flash: short
        action: light.turn_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.side_garage_door
        state: 'off'
      sequence:
      - target:
          entity_id: light.hall_night_light
        data:
          rgb_color:
          - 173
          - 216
          - 230
          brightness_pct: 50
        action: light.turn_on
>>>>>>> e9374e6 (updated automations)
  mode: single
- id: '1758304107678'
  alias: Roxanne Leaves for work
  description: ''
  triggers:
  - device_id: c3b47c069b52225f026dd58a98c8cd4e
    domain: device_tracker
    entity_id: af267c86e9af1913e5eb1d34d86a248d
    type: leaves
    trigger: device
    zone: zone.home
  conditions:
  - condition: time
    after: 07:00:00
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.goodnight_john_boy
  mode: single
