# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Monolithic includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MariaDB recorder
recorder:
  db_url: !secret mariadb_url

# HTTP proxy settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.80.100