# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Monolithic includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HTTP proxy settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.80.100
    
recorder:
  purge_keep_days: 7
  auto_purge: true
  include:
    domains:
      - sensor
      - switch
      - light
      - binary_sensor
      
history: {}
logbook: {}