# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Hybrid includes: UI + modular YAML
automation:
  - !include automations.yaml
  - !include_dir_merge_list automations/

script:
  - !include scripts.yaml
  - !include_dir_merge_list scripts/

scene:
  - !include scenes.yaml
  - !include_dir_merge_list scenes/

# MariaDB recorder
recorder:
  db_url: !secret mariadb_url

# HTTP proxy settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.80.100