# ─────────────────────────────────────────────
# File: alerts.yaml
# Purpose: Reactive alerts for door sensors and lighting
# ─────────────────────────────────────────────

- alias: alert_side_garage_door_open
  description: Flash hall night light if garage door opens after 9:30pm
  trigger:
    - platform: state
      entity_id: binary_sensor.side_garage_door
      to: "on"
  condition:
    - condition: time
      after: "21:30:00"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hall_night_light
      data:
        rgb_color: [242, 7, 7]
        flash: short
  mode: single

- alias: alert_side_garage_door_closed
  description: Turn off hall night light when garage door closes
  trigger:
    - platform: state
      entity_id: binary_sensor.side_garage_door
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.hall_night_light
  mode: single