# ─────────────────────────────────────────────
# File: environment.yaml
# Purpose: Environmental triggers like temperature-based fan control
# ─────────────────────────────────────────────

- alias: environment_garage_fan_on
  description: Turn on garage fan if temperature exceeds 85°F
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_realfeel_temperature
      above: 85
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.garage_fan
  mode: single

- alias: environment_garage_fan_off
  description: Turn off garage fan if temperature drops below 84°F
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_realfeel_temperature
      below: 84
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.garage_fan
  mode: single