# ─────────────────────────────────────────────
# File: routines.yaml
# Purpose: Scene-based routines and bedtime logic
# ─────────────────────────────────────────────

- alias: routine_lets_relax
  description: Activate relaxation scene 5 minutes before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.lets_relax_scene
  mode: single

- alias: routine_time_for_bed
  description: Run bedtime script and optionally activate scene
  trigger:
    - platform: time
      at: "23:30:00"
    - platform: conversation
      command: "Time for bed"
  condition:
    - condition: state
      entity_id: light.kitchen_accent
      state: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.time_for_bed_script_2
    - service: scene.turn_on
      target:
        entity_id: scene.goodnight_john_boy
      enabled: false
  mode: single